# This is a basic workflow to help you get started with Actions

name: CI on remote repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: PromyLOPh/guix-install-action@v1.2.2
        name: Install GNU Guix

      - run: guix shell -m manifest.scm make install
        name: Install project dependencies (including dev ones)

      # Runs a set of commands using the runners shell
      - name: Lint
        run: guix shell -m manifest.scm make lint
